### ISSUE TITLE
50% poison rate?

### ISSUE THREAD

**Issue by RorschachChen** [Ekko-zn/IJCAI2022-Backdoor#1]
If I am not getting it wrong, this method in train.py uses a 50% poison rate if we look at this method from the aspect of poisoning. I understand this method assumes the attacker has full control of the training set and the training process.

**Comment by Ekko-zn** [comment]
Yes, the attacker has full control of the training set and the training process in our threat model.

**Comment by Ekko-zn** [comment]
> If I am not getting it wrong, this method in train.py uses a 50% poison rate if we look at this method from the aspect of poisoning. I understand this method assumes the attacker has full control of the training set and the training process.

Yes, the attacker has full control of the training set and the training process in our threat model.
